version: '2'
services:
     worker:
          build:
               context: .
               dockerfile: dockerfile
          volumes:
               - .:/app
          links:
               - rabbit
          depends_on:
               - rabbit
     rabbit:
          hostname: rabbit
          image: rabbitmq:latest
          environment:
               - RABBITMQ_DEFAULT_USER=admin
               - RABBITMQ_DEFAULT_PASS=mypass
          ports:
               - "5672:5672"
